# Generated by Django 4.1.3 on 2022-12-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_options_review_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["title", "-created"]},
        ),
    ]
