# Generated by Django 4.1.3 on 2022-11-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_tag_rename_create_project_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="vote_ration",
            new_name="vote_ratio",
        ),
    ]
